apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: NodePort
  selector:
    app: mlflow-server
  ports:
  - name: mlflow-port
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30000